def M11():
	a = "[FBAN/FB4A;FBAV/"+str(random.randint(11,69))+'.0.0.'+str(random.randrange(9,49))+'.'+str(random.randint(11,313)) +";FBBV/"+str(random.randint(1111111,7777777))              
	b = ";[FBAN/Orca-Android;FBAV/19.0.0.19.42;FBLC/es_ES;FBBV/6398209;FBCR/CELTELHND;FBMF/alps;FBBD/Bmobile;FBDV/AX610;FBSV/4.2.2;FBCA/armeabi-v7a:armeabi;FBDM/{density=1.0,width=320,height=480};FB_FW/1;]"
	ua = a+b
	return ua
